---
# tasks file for haproxy
- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present
  
  become: true

- name: Configure haproxy load balancing
  template:
    src: ./files/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

  become: true

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true

  become: true
