---
- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml
    
    - name: Debug
      debug:
        msg: "{{ GUID }}-project" 

    - name: Debug Instance
      debug:
        msg: "{{ instance.keypair }}"
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance

    - name: Create Instance
      openstack.cloud.server:
        cloud: "{{ GUID }}-project"
        name: "{{ instance.name }}"
        image: "{{ instance.image }}"
        key_name: "{{ instance.keypair }}"
        flavor: "{{ instance.flavor }}"
        security_groups: "{{ instance.security_group }}"
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ instance.internal_network }}"
        meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}},HostGroup={{instance.metadata.HostGroup}}"

      loop: "{{ instances }}"
      loop_control:
        loop_var: instance
     
    - name: Collection instance info
      os_server_info:
        cloud: "{{ GUID }}-project"
      register: instances

    - name: Build In-Memory inventory
      add_host:
        host: "{{ instance.name }}"
        group: "{{ instance.metadata.HostGroup }}"
        ansible_host: "{{ instance.private_v4 }}"
        ssh_private_key_file: "{{ home }}/.ssh/{{ GUID }}key.pem"
      when: instance.metadata.AnsibleGroup == "osp_instances"
      loop: "{{ instances.openstack_servers }}"
      loop_control:
        loop_var: instance
