---

- name: Configure database servers
  hosts: database_serversAAAAA
  gather_facts: false
  roles:
    - role: common
    - role: postgres

- name: Configure apps servers
  hosts: app_serversAAAAAAAAAAAAA
  roles:
    - role: common
    - role: apps

- name: Configure load balancers 
  hosts: load_balancers
  roles:
    - role: common
    - role: haproxy
