---

- name: Configure database servers
  hosts: database_serversAAAAA
  gather_facts: false
  roles:
    - role: common
    - role: postgres

- name: Configure apps servers
  hosts: app_servers
  roles:
    - role: common
    - role: apps
