---
# tasks file for roles/common
#
- name: Gather network facts
  setup:
    gather_subset:
      - 'network'
  delegate_facts: true
  delegate_to: localhost
  connection: local

- name: DNS IP updated
  community.general.nmcli:
    conn_name: eth0
    type: ethernet
    dns4_ignore_auto: yes
    dns4: 192.168.50.73  
# Hay que hacer que borre los anteriores
    dns4_search:
      - example.com
    state: present

  register: network_update  

  become: yes
  become_user: root

- name: restart network manager
  service:
    name: NetworkManager
    state: restarted
  when: network_update.changed | bool

  become: yes
  become_user: root

- name: install katello-ca-consumer package
  yum:
    name: "{{ satellite_katello_cert }}" 
    state: present
    disable_gpg_check: true

  become: yes
  become_user: root
  ignore_errors: yes

- name: register system and attach subs
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true
    rhsm_baseurl: "{{ satellite_url }}"
    force_register: yes

  become: yes
  become_user: root
