---
# tasks file for roles/common
#
- name: Gather network facts
  setup:
    gather_subset:
      - 'network'
  delegate_facts: true
  delegate_to: localhost
  connection: local

- name: Configure Control Node as DNS SERVER
  lineinfile:
    state: present
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  loop:
    - PEERDNS=no
    - DNS1={{ hostvars.localhost.ansible_default_ipv4.address }}
  register: network_update

- name: restart network manager
  service:
    name: NetworkManager
    state: restarted
  when: network_update.changed | bool

- name: install katello-ca-consumer package
  yum:
    name: "{{ satellite_katello_cert }}" 
    state: present
    disable_gpg_check: true

  become: yes
  become_user: root
  ignore_errors: yes

- name: register system and attach subs
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true
    rhsm_baseurl: "{{ satellite_url }}"
    force_register: yes

  become: yes
  become_user: root
